/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.2 Component Pack 6
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <USBFS.h>
#include <USBFS_audio.h>
#include <USBFS_cdc.h>
#include <USBFS_hid.h>
#include <USBFS_midi.h>
#include <Pin_StatusLED_aliases.h>
#include <Pin_StatusLED.h>
#include <SWDCLK_aliases.h>
#include <SWDCLK.h>
#include <SWDXRES_aliases.h>
#include <SWDXRES.h>
#include <SWDIO_aliases.h>
#include <SWDIO.h>
#include <Pin_HWVersionA_aliases.h>
#include <Pin_HWVersionA.h>
#include <Bootloadable.h>
#include <I2CHW.h>
#include <I2CHW_PVT.h>
#include <Pin_I2C_SCL_aliases.h>
#include <Pin_I2C_SCL.h>
#include <Pin_I2C_SDA_aliases.h>
#include <Pin_I2C_SDA.h>
#include <Clock_I2C.h>
#include <UART_Bridge.h>
#include <Clock_UART.h>
#include <Pin_UART_Tx_aliases.h>
#include <Pin_UART_Tx.h>
#include <Pin_UART_Rx_aliases.h>
#include <Pin_UART_Rx.h>
#include <Pin_SDAPullUp_Enable_aliases.h>
#include <Pin_SDAPullUp_Enable.h>
#include <Pin_SCLPullUp_Enable_aliases.h>
#include <Pin_SCLPullUp_Enable.h>
#include <Pin_HWVersionB_aliases.h>
#include <Pin_HWVersionB.h>
#include <Pin_HWVersionC_aliases.h>
#include <Pin_HWVersionC.h>
#include <Pin_HWVersionD_aliases.h>
#include <Pin_HWVersionD.h>
#include <Pin_HWVersionE_aliases.h>
#include <Pin_HWVersionE.h>
#include <Pin_HWVersionF_aliases.h>
#include <Pin_HWVersionF.h>
#include <isr_UsbSuspend.h>
#include <Clock_UsbSuspend.h>
#include <Timer_UsbSuspend.h>
#include <USBFS_Dm_aliases.h>
#include <USBFS_Dm.h>
#include <USBFS_VBUS_aliases.h>
#include <USBFS_VBUS.h>
#include <USBFS_Dp_aliases.h>
#include <USBFS_Dp.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>

/*[]*/

