# THIS FILE IS AUTOMATICALLY GENERATED
# Project: \\psf\Home\Desktop\USB-Audio-PSOC5LP\Firmware\KitProg version 2_03\KitProg\KitProg.cydsn\KitProg.cyprj
# Date: Fri, 28 Aug 2015 22:33:38 GMT
#set_units -time ns
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyPLL_OUT} -period 15.625 -waveform {0 7.8125} [list [get_pins {ClockBlock/pllout}]]
create_clock -name {CyILO} -period 10000 -waveform {0 5000} [list [get_pins {ClockBlock/ilo}] [get_pins {ClockBlock/clk_100k}] [get_pins {ClockBlock/clk_1k}] [get_pins {ClockBlock/clk_32k}]]
create_clock -name {CyMASTER_CLK} -period 15.625 -waveform {0 7.8125} [list [get_pins {ClockBlock/clk_sync}]]
create_generated_clock -name {Clock_I2C} -source [get_pins {ClockBlock/clk_sync}] -edges {1 5 9} [list [get_pins {ClockBlock/dclk_glb_0}]]
create_generated_clock -name {Clock_UART} -source [get_pins {ClockBlock/clk_sync}] -edges {1 833 1665} [list [get_pins {ClockBlock/dclk_glb_1}]]
create_generated_clock -name {Clock_UsbSuspend} -source [get_pins {ClockBlock/clk_sync}] -edges {1 1281 2561} [list [get_pins {ClockBlock/dclk_glb_2}]]
create_clock -name {Clock_UsbSuspend(fixed-function)} -period 20000 -waveform {0 10000} [get_pins {ClockBlock/dclk_glb_ff_2}]
create_generated_clock -name {CyBUS_CLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 2 3} [list [get_pins {ClockBlock/clk_bus_glb}]]

set_false_path -from [get_pins {__ONE__/q}]

# Component constraints for \\psf\Home\Desktop\USB-Audio-PSOC5LP\Firmware\KitProg version 2_03\KitProg\KitProg.cydsn\TopDesign\TopDesign.cysch
# Project: \\psf\Home\Desktop\USB-Audio-PSOC5LP\Firmware\KitProg version 2_03\KitProg\KitProg.cydsn\KitProg.cyprj
# Date: Fri, 28 Aug 2015 22:33:26 GMT
