/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.2 Component Pack 6
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <Bootloader.h>
#include <Pin_PSoC4A_XRES_aliases.h>
#include <Pin_PSoC4A_XRES.h>
#include <Pin_Status_LED_aliases.h>
#include <Pin_Status_LED.h>
#include <Clock_LED_1.h>
#include <USBFS.h>
#include <USBFS_audio.h>
#include <USBFS_cdc.h>
#include <USBFS_hid.h>
#include <USBFS_midi.h>
#include <PWM.h>
#include <USBFS_Dm_aliases.h>
#include <USBFS_Dm.h>
#include <USBFS_Dp_aliases.h>
#include <USBFS_Dp.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>

/*[]*/

